image: python:3.9

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip
    - .venv/

before_script:
  - python -V
  - python -m venv .venv
  - source .venv/bin/activate
  - python -m pip install --upgrade pip
  - python -m pip install poetry
  - poetry install

stages:
  - lint
  - test

lint:
  stage: lint
  script:
    - flake8 --jobs 4 --statistics --show-source todo
    - pylint --jobs 4 --rcfile=setup.cfg todo
    - mypy todo
    - black --line-length=80 --target-version=py39 --skip-string-normalization --check todo

test:
  stage: test
  script:
    - pytest -v tests
